### PR TITLE
Sync volar v2.0.x

### PR DESCRIPTION
**Pull request by yaegassy**
In progress...

---

<details><summary> This problem has been resolved.</summary><div>
If `diagnosticModel` is a `push`, the 2.0.x language server crashes after startup...

~Symptoms observed on `v2.0.2` language server.~
~**Edit**: The situation remains the same with `v2.0.4` of the language server.~
**Edit**: The situation remains the same with `v2.0.5` of the language server. Maybe there is a problem with coc.nvim itself, etc...

~By the way, if `diagnosticModel` is `pull`, the language server works without crashing after startup, but with `<script>` block, LSP's core features like IntelliSense and Diagnositcs don't work.~
**Update**: By the way, if the `diagnosticModel` setting is `pull`, the language server runs without crashing after startup.

**Log**:

```
// ...snip
[Trace - 17:46:16.248] Received request 'workspace/diagnostic/refresh - (8)'.
[Trace - 17:46:16.248] Sending response 'workspace/diagnostic/refresh - (8)'. Processing request took 0ms
/Users/yaegassy/_Dev/source/coc-volar/node_modules/vscode-jsonrpc/lib/common/connection.js:565
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Unhandled method workspace/diagnostic/refresh
    at handleResponse (/Users/yaegassy/_Dev/source/coc-volar/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)
    at handleMessage (/Users/yaegassy/_Dev/source/coc-volar/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)
    at processMessageQueue (/Users/yaegassy/_Dev/source/coc-volar/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/Users/yaegassy/_Dev/source/coc-volar/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at process.processImmediate (node:internal/timers:478:21) {
  code: -32601,
  data: undefined
}

Node.js v20.11.1
[Error - 17:46:16.264] Connection to server got closed. Server will not be restarted.
```

**DEMO (mp4)**:

https://github.com/yaegassy/coc-volar/assets/188642/9e4a49b3-e6cb-400f-8f56-0a52e8f40281

</div></details>

### CODE REVIEW

**Comment by yaegassy** [comment]
### TODO

> - typescript-plugin: renamed package to @vue/typescript-plugin (#3910)

It appears that the typescript plugin has been renamed.

- Before
  - typescript-vue-plugin
    - https://www.npmjs.com/package/typescript-vue-plugin
- After
  - @vue/typescript-plugin
    - https://www.npmjs.com/package/@vue/typescript-plugin

---

Consider adding the `@vue/typescript-plugin` package to coc-volar itself and adding the following settings.

```
// ...snip
    "typescriptServerPlugins": [
      {
        "name": "@vue/typescript-plugin",
        "enableForWorkspaceTypeScriptVersions": true
      }
    ]
// ...snip
```

**Comment by yaegassy** [comment]
I found a pattern that works, but... It seems that I have to get coc-tsserver to work first.

1. First, set `vue.server.diagnosticModel` to `pull` in `coc-settings.json`.

   ```jsonc
   {
     // ...snip
     "vue.server.diagnosticModel": "pull",
     // ....snip
   }
   ```

1. Install `@vue/typescript-plugin` in coc-volar itself.

1. Add the `contributes.typescriptServerPlugins` setting in coc-volar's `package.json`. As an additional note, include `vue` in the `languages` setting.

   ```
       // ...snip
       "typescriptServerPlugins": [
         {
           "name": "@vue/typescript-plugin",
           "enableForWorkspaceTypeScriptVersions": true,
           "languages": [
             "typescript",
             "vue"
           ]
         }
       ]
   ```

3. Open the `ts` file before opening the `vue` file so that `coc-tsserver` runs first.

4. Various core lsp-features, such as IntelliSense, Diagnostics and more, will also work in `<script>` block.

**Comment by yaegassy** [comment]
## INFO

`typescript-vue-plugin` and `@vue/typescript-plugin` conflict and cause errors.

If you are using `@yaegassy/coc-typescript-vue-plugin` when the language server is v2.0.x, you need to uninstall it.

**Comment by fannheyward** [comment]
> diagnosticModel is a push, the 2.0.x language server crashes

Any logs? I can help to debug on coc.nvim's diagnostic pull mode.

**Comment by fannheyward** [comment]
Sorry for the stupid question, but how to make Volar to work in VSCode? I use `npm create vue@latest` to create an Vue project, install the https://marketplace.visualstudio.com/items?itemName=Vue.volar extension (the volar one?), open the `App.vue` file, but VSCode can't jump to HelloWorld.

I wrote some Vue 2 codes about five years ago, but failed to run Vue 3 with Volar 😞

**Comment by yaegassy** [comment]
@fannheyward Sorry it took me so long to reply. Thanks for your concern. I am currently too busy with work to spend much time concentrating on Vim/Neovim etc... :(

First of all, there is a setting that vue langauge sever runs without crashing with an error after startup, so I will proceed with that as the default value.

**Comment by yaegassy** [comment]
coc-typescript-vue-plugin has been changed to archive repository.

- <https://github.com/yaegassy/coc-typescript-vue-plugin>
  - `@yaegassy/coc-typescript-vue-plugin`

**Comment by yaegassy** [comment]
## Summary to date

- Change default value of `vue.server.diagnosticModel` to `pull`
- Modified the startup process of the `coc-volar` extension itself to start `tsserver` together.
  - `coc-tsserver` or `coc-tsserver-dev` extension required.
  - Various core LSP-features, such as IntelliSense, Diagnostics and more, will also work in `<script>` block.
- Added `@vue/typescript-plugin` package to the extension itself and added `typescriptServerPlugins` setting.

**DEMO (mp4)**:

https://github.com/yaegassy/coc-volar/assets/188642/0e2092b6-199b-4629-9a40-38692501b6a6

**Comment by yaegassy** [comment]
coc-volar-tools has been changed to archive repository.

- <https://github.com/yaegassy/coc-volar-tools>
  - `@yaegassy/coc-volar-tools`

**Comment by fannheyward** [comment]
I'm debugging on the `push` model issue. Looks like volar.js will disable `diagnosticProvider` when diagnosticModel = push

https://github.com/volarjs/volar.js/blob/e56916097fe7be2920aab6592a564a8e2ceafd14/packages/language-server/lib/server.ts#L147C37-L149

From trace logs, no `diagnosticProvider` in initialize response.

Then, Volar sends `workspace/diagnostic/refresh` to client, coc.nvim responses but the server didn't handle it. The question: why server request this at `diagnosticProvider`?

**Comment by fannheyward** [comment]
Fixed on coc.nvim https://github.com/neoclide/coc.nvim/pull/4928

**Comment by yaegassy** [comment]
@fannheyward Thanks fann, I have checked that the `diagnosticsModel` issue has been resolved in my environment as well.

However, not all `coc.nvim` users use `master`, so for now we will use `pull` as the default value.

**Comment by yaegassy** [comment]
There seem to be many issue report on the upstream side at the moment. I am sure that bug fixes, tweaks, etc. will continue to be made, so I will take a wait-and-see approach to this PR merge and release.

**Comment by yaegassy** [comment]
I will merge this Pull Request since it works fine in my environment.

**TODO**: I will commit adjustments to the README later.

**Pull request merged**
