### PR TITLE
Sync volar v1.3.3

### PR DESCRIPTION
**Pull request by yaegassy**

### CODE REVIEW

**Comment by yaegassy** [comment]
Hi, @johnsoncodehk. volar `v1.3.3` appears to have issues with diagnostics. Here's a demo in VS Code. Similar symptoms were observed with coc-volar as well.

https://user-images.githubusercontent.com/188642/226222814-41a40ad1-3de1-4ec6-ac48-55436c22e80b.mp4

**Comment by johnsoncodehk** [comment]
Oh this is serious...

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/vuejs/language-tools/commit/4ba67572e7bd401606b3d1bf94409879cb3b0f89.

**Comment by yaegassy** [comment]
Thanks!

**Pull request closed without merging**
