### PR TITLE
chore(deps): update to volar v0.27.9

### PR DESCRIPTION
**Pull request by yaegassy**

### CODE REVIEW

**Comment by yaegassy** [comment]
@johnsoncodehk 

I wasn't sure if I should report this in the volar issue, but I will comment on this PR of mine. (I will report it to volar issue if needed).

There seems to be an error in CodeLens's "ref sugar (take2)" to disable. (v0.27.9)

I'm not sure if this is the proper way to reproduce the problem, but it does in my environment.

## Error

**coc-volar (coc.nvim)**:

```
[coc.nvim]: Error on "codeLensAction": Request workspace/executeCommand failed with message: Cannot read property 'uri' of undefined
```

**VSCode's volar extension**:

```
[Error - 1:37:48] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with message: Cannot read property 'uri' of undefined
  Code: -32603 
```

## DEMO: VSCode's volar extension 

### [OK] When the cursor is around ref

https://user-images.githubusercontent.com/188642/131258747-f2de1eb2-e0a6-4092-a275-9d42f4b3e12c.mp4

### [NG] If the cursor is in any other location

https://user-images.githubusercontent.com/188642/131258754-97135ede-b6f8-4393-84a8-5d92e69912c2.mp4

**Comment by johnsoncodehk** [comment]
It's weird, and I can't see this problem. Could you try to debug it?

1. Run Volar on Debug Mode, see (2) in https://github.com/johnsoncodehk/volar/discussions/413.

2. Attach to document server.
螢幕截圖 2021-08-30 上午1 28 17

3. Select Caught Exceptions.
螢幕截圖 2021-08-30 上午1 27 33

4. Click "ref sugar (take 2)" to trigger the error.

5. If Debugger caught the error, check "Call Stack" to find last volar executive code.

**Comment by yaegassy** [comment]
@johnsoncodehk  Thanks reply. 🙇

If johnsoncodehk can't reproduce it, then it's probably a problem with my environment, but...

In my environment, I created a project with volar-starter and vite, and confirmed this problem.

I would like to find time to try debugging with VSCode using the method you taught me.

**Comment by yaegassy** [comment]
@johnsoncodehk I tried to debug with VSCode, but I couldn't figure out how to use the debugger correctly. Sorry about that.

---

By increasing the number of seconds to sleep, as in the recent fix for "setup sugar", the error no longer occurs.

- fix: setup sugar convert failed
  - <https://github.com/johnsoncodehk/volar/commit/9b1bf26185a087dc0565a575d812aaa0a6d168e3>

### Before

https://user-images.githubusercontent.com/188642/131296281-a80747f6-98f5-4e02-b5e7-95002ed81fb0.mp4

### After

**diff**:

```
diff --git a/packages/vscode-vue-languageservice/src/commands/unuseRefSugar.ts b/packages/vscode-vue-languageservice/src/commands/unuseRefSugar.ts
index 745bf83..21586b1 100644
--- a/packages/vscode-vue-languageservice/src/commands/unuseRefSugar.ts
+++ b/packages/vscode-vue-languageservice/src/commands/unuseRefSugar.ts
@@ -36,7 +36,7 @@ export function register(context: ApiLanguageServiceContext) {
                if (edits?.length) {

                        await connection.workspace.applyEdit({ changes: { [uri]: edits } });
-                       await shared.sleep(0);
+                       await shared.sleep(200);

                        const errors = await getDiagnostics(uri, () => { }) ?? [];
                        await shared.sleep(0);
```

https://user-images.githubusercontent.com/188642/131296320-5a8eade0-c0ff-423a-82f1-f88132c35819.mp4

**Comment by johnsoncodehk** [comment]
If you scrolling up call stack, can you find execute line come from vscode-vue-languageservice module?

螢幕截圖 2021-08-30 下午2 49 39

If you can't, never mind! At least we know how to fix it. Thanks for your help!

**Comment by yaegassy** [comment]
I know that `vscode-languageclient/lib/common/client.js` gave an error, but I couldn't tell if `vscode-vue-languageservice` was the cause or not. :(

**Re: check-error**:

https://user-images.githubusercontent.com/188642/131298926-629d5e75-9ae3-47db-8732-c8195c27cb2f.mp4

**Comment by johnsoncodehk** [comment]
Should be fixed in 0.27.10, thank you!

**Comment by yaegassy** [comment]
Thanks!

**Pull request merged**
