### PR TITLE
refactor: Sync to volar 0.26.12

### PR DESCRIPTION
**Pull request by johnsoncodehk**

### CODE REVIEW

**Comment by yaegassy** [comment]
Thanks for the pull request, I have checked it in my environment and it works fine, so I will merge it.

> 🎉 feat: support for vue 2 template

That's great!

**Comment by johnsoncodehk** [comment]
It seem have a regression, please don't release for now. 😅

https://github.com/johnsoncodehk/volar/issues/352

**Comment by johnsoncodehk** [comment]
Please update to 0.26.13 to fix https://github.com/johnsoncodehk/volar/issues/352, thanks!

**Comment by yaegassy** [comment]
Thanks!!

**Pull request merged**
