### PR TITLE
Sync volar v1.0.0

### PR DESCRIPTION
**Pull request by yaegassy**
Upstream is currently in ~alpha~ ~beta~ **rc** version, so this PR will not be merged yet.

### CODE REVIEW

**Comment by yaegassy** [comment]
In `1.0.0-beta.2`, there were some changes such as initializationOptions, etc. I tried to reflect it with reference to upstream, but the server cannot start.

I felt that `fillInitializeParams` and `getFillInitializeParams` were not working properly in `coc-volar`.

Will check again for updates in the next release (`1.0.0-beta.3`?)

**Comment by johnsoncodehk** [comment]
Seems coc.nvim language client has different API, can you try `fillClientCapabilities`?

```ts
    const client = new LanguageClient(id, name, serverOptions, clientOptions);
    context.subscriptions.push(client.start());

    client.registerFeature({
      // fillInitializeParams() { }, // seems should be use fillClientCapabilities
      fillClientCapabilities(capabilities) {
        capabilities.textDocument.formatting = undefined;
      },
      initialize() {
        // just for fix types, not sure if this is needed
        // ...
      },
      dispose() {
        // ...
      }
    })
```

**Comment by yaegassy** [comment]
@johnsoncodehk Thanks for catching up. 🙇

I tried it briefly and it doesn't seem to work. I'll try things again later.

**Comment by johnsoncodehk** [comment]
Maybe have to see how fillClientCapabilities works, I'll see later. (And I just released v1.0.0-beta.3)

**Comment by yaegassy** [comment]
@johnsoncodehk Uploaded code focused on server activation of the `volar` to a separate repository.

- <https://github.com/yaegassy/coc-volar-sandbox>

I also checked the client's `initializationOptions` and `documentSelector` to be sure, but there seems to be no problem there.

I tried `fillClientCapabilities` but unfortunately it could not start...

**initializationOptions**:

> vue-semantic-server -> "serverMode": 0
> vue-syntactic-server -> "serverMode": 2

```
{
  "serverMode": 0,
  "diagnosticModel": 1,
  "textDocumentSync": 2,
  "typescript": {
    "tsdk": "/Users/yaegassy/sandbox/coc-volar/node_modules/typescript/lib/tsserverlibrary.js",
    "isWorkspacePath": false
  },
  "petiteVue": { "processHtmlFile": false },
  "vitePress": { "processMdFile": false }
}
```

**documentSelector**:

> documentSelector is also correct.

```
[
  { "scheme": "file", "languages": "vue" },
  { "scheme": "file", "languages": "javascript" },
  { "scheme": "file", "languages": "typescript" },
  { "scheme": "file", "languages": "javascriptreact" },
  { "scheme": "file", "languages": "typescriptreact" },
  { "scheme": "file", "languages": "json" }
]
```

This is a log from the coc.nvim side, so it may not be helpful, but I'll put it here to give you an idea of what I'm talking about.

**Log**:

> initialization failed ...

```
2022-10-03T14:59:45.889 ERROR (pid:91041) [language-client-client] - Server vue-semantic-server initialization failed. ResponseError2: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
    at handleResponse (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12025:11)
    at processImmediate (node:internal/timers:466:21) {
  code: -32603,
  data: undefined
}
2022-10-03T14:59:45.890 ERROR (pid:91041) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-10-03T14:59:45.890 ERROR (pid:91041) [server] - unhandledRejection  Promise {
  <rejected> ResponseError2: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
      at handleResponse (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12216:40)
      at processMessageQueue (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12039:13)
      at Immediate.<anonymous> (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12025:11)
      at processImmediate (node:internal/timers:466:21) {
    code: -32603,
    data: undefined
  },
  dispose: [Function (anonymous)]
} ResponseError2: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
    at handleResponse (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12025:11)
    at processImmediate (node:internal/timers:466:21) {
  code: -32603,
  data: undefined
}
2022-10-03T14:59:45.892 ERROR (pid:91041) [language-client-client] - Server vue-syntactic-server initialization failed. ResponseError2: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
    at handleResponse (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12025:11)
    at processImmediate (node:internal/timers:466:21) {
  code: -32603,
  data: undefined
}
2022-10-03T14:59:45.893 ERROR (pid:91041) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-10-03T14:59:45.893 ERROR (pid:91041) [server] - unhandledRejection  Promise {
  <rejected> ResponseError2: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
      at handleResponse (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12216:40)
      at processMessageQueue (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12039:13)
      at Immediate.<anonymous> (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12025:11)
      at processImmediate (node:internal/timers:466:21) {
    code: -32603,
    data: undefined
  },
  dispose: [Function (anonymous)]
} ResponseError2: Request initialize failed with message: Cannot read properties of undefined (reading 'createLanguageService')
    at handleResponse (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12025:11)
    at processImmediate (node:internal/timers:466:21) {
  code: -32603,
  data: undefined
}
```

**Comment by johnsoncodehk** [comment]
Can you try update `"tsdk": "/Users/yaegassy/sandbox/coc-volar/node_modules/typescript/lib/tsserverlibrary.js"` to "tsdk": "/Users/yaegassy/sandbox/coc-volar/node_modules/typescript/lib"?

**Comment by yaegassy** [comment]
@johnsoncodehk  Ah, Server is now up and running! 🙇

**Comment by yaegassy** [comment]
## "volar.action.showVirtualFiles" command

### DEMO (mp4)

coc-volar's `volar.action.showVirtualFiles` command only supports displaying virtual files.

https://user-images.githubusercontent.com/188642/193977896-273e705b-5d26-49ee-b1d4-2255a39fcc08.mp4

**Pull request merged**
